<?php

namespace AppBundle\Repository;

/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadTrackWithArtists(int $limit = 50)
    {
        $qb = $this->createQueryBuilder('track');

        $qb
          ->leftJoin('track.artist', 'artist')
          ->select('track', 'artist')
          ->setMaxResults($limit);
        return $qb->getQuery()->execute();
    }
}
